export const APP_NAME = 'Church Projector'
export const TARGET_WIDTH = 1920
export const TARGET_HEIGHT = 1080

export const IPC_CHANNELS = {
  PROJECTION_COMMAND: 'projection:command',
  PROJECTION_STATE: 'projection:state',
  MEDIA_PLAYBACK_STATE: 'projection:mediaPlayback',
  SHOW_PROJECTION: 'projection:show',
  SHORTCUT_FIRED: 'shortcut:fired',
  GET_DISPLAYS: 'displays:get',
  GET_SETTINGS: 'settings:get',
  SET_SETTINGS: 'settings:set',
  SETTINGS_UPDATED: 'settings:updated',
  GET_BIBLE_FONTS: 'fonts:list',
  ADD_BIBLE_FONTS: 'fonts:add',
  DELETE_BIBLE_FONT: 'fonts:delete',
  BIBLE_FONTS_UPDATED: 'fonts:updated',
  GET_MEDIA: 'media:list',
  MEDIA_UPDATED: 'media:updated',
  SCAN_MEDIA: 'media:scan',
  GET_LIVE_MEDIA: 'media:listLive',
  LIVE_MEDIA_UPDATED: 'media:liveUpdated',
  GET_BIBLE_MEDIA: 'media:listBible',
  BIBLE_MEDIA_UPDATED: 'media:bibleUpdated',
  GET_MEDIA_META: 'media:meta:get',
  SET_MEDIA_CATEGORY: 'media:meta:setCategory',
  SET_MEDIA_TODAY: 'media:meta:setToday',
  CLEAR_MEDIA_TODAY: 'media:meta:clearToday',
  MEDIA_META_UPDATED: 'media:meta:updated',
  GET_AUDIO: 'audio:list',
  AUDIO_UPDATED: 'audio:updated',
  GET_AUDIO_STATE: 'audio:getState',
  SET_AUDIO_STATE: 'audio:setState',
  SCAN_AUDIO: 'audio:scan',
  GET_AUDIO_PLAYLISTS: 'audio:playlists:get',
  SAVE_AUDIO_PLAYLIST: 'audio:playlists:save',
  DELETE_AUDIO_PLAYLIST: 'audio:playlists:delete',
  GET_SONGS: 'songs:get',
  SAVE_SONG: 'songs:save',
  DELETE_SONG: 'songs:delete',
  SONGS_UPDATED: 'songs:updated',
  GET_ALBUMS: 'albums:get',
  SAVE_ALBUM: 'albums:save',
  DELETE_ALBUM: 'albums:delete',
  ALBUMS_UPDATED: 'albums:updated',
  GET_BIBLE_VERSIONS: 'bible:getVersions',
  GET_BIBLE_BOOKS: 'bible:getBooks',
  GET_BIBLE_BOOK_STATS: 'bible:getBookStats',
  SEARCH_VERSE: 'bible:searchVerse',
  SHOW_OPEN_DIALOG: 'dialog:showOpen'
} as const
